### ISSUE TITLE
Hi Mr Peel can this Load on Android or is it only Iphone Friendly I cants get it to load on my Glalxsy s7

### ISSUE THREAD

**Issue by Tronce** [mrpeel/smes-on-the-go#1]
Hi Mr Peel can this Load on Android or is it only Iphone Friendly I cant get it to load on my Glalxsy s7
Regards From
Terry Clark
terryclark@westnet.com.au
terry.clark@speedies.com.au
0408429105

Speedie Development Consultants Surveyors and egineers

**Comment by mrpeel** [comment]
The application is just a mobile website so it's not platform specific.  I originally developed it when I had an LG Andoird phone and I now have a Oneplus Android phone and it works on both of those devices. 

The only obvious thing to check is that you are using the Chrome browser.  I believe Samsung have their own browser.  I've only tested it using Chrome on Android, Chrome on iOS and Safari on iOs.

**Comment by Tronce** [comment]
Thanks Neil I am opening it in chrome but the map doesn't load I'm running avast on my phone could that be blocking it ?Maybe I should ditch avast ?Regards From Terry Clark 


Sent from my SAMSUNG Galaxy S7 on the Telstra Mobile Network
-------- Original message --------From: Neil Kloot <notifications@github.com> Date: 3/03/2017  4:45 PM  (GMT+10:00) To: mrpeel/smes-on-the-go <smes-on-the-go@noreply.github.com> Cc: Tronce <terryclark@westnet.com.au>, Author <author@noreply.github.com> Subject: Re: [mrpeel/smes-on-the-go] Hi Mr Peel can this Load on Android or is it only Iphone Friendly I cants get it to load on my Glalxsy s7 (#1) 
The application is just a mobile website so it's not platform specific.  I originally developed it when I had an LG Andoird phone and I now have a Oneplus Android phone and it works on both of those devices.
The only obvious thing to check is that you are using the Chrome browser.  I believe Samsung have their own browser.  I've only tested it using Chrome on Android, Chrome on iOS and Safari on iOs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrpeel/smes-on-the-go","title":"mrpeel/smes-on-the-go","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mrpeel/smes-on-the-go"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrpeel in #1: The application is just a mobile website so it's not platform specific.  I originally developed it when I had an LG Andoird phone and I now have a Oneplus Android phone and it works on both of those devices. \r\n\r\nThe only obvious thing to check is that you are using the Chrome browser.  I believe Samsung have their own browser.  I've only tested it using Chrome on Android, Chrome on iOS and Safari on iOs."}],"action":{"name":"View Issue","url":"https://github.com/mrpeel/smes-on-the-go/issues/1#issuecomment-283871233"}}}

**Comment by Tronce** [comment]
Hi Neil
I've got it working I changed a few  settings and reloaded it In chrome 
I think it was my pop up blocker setting in chrome it's all good now fantastic link Well done and many thanks
You should be selling it as an app 
Kind Regards TerryClark 


Sent from my SAMSUNG Galaxy S7 on the Telstra Mobile Network

Sent from my SAMSUNG Galaxy S7 on the Telstra Mobile Network
-------- Original message --------From: Neil Kloot <notifications@github.com> Date: 3/03/2017  4:45 PM  (GMT+10:00) To: mrpeel/smes-on-the-go <smes-on-the-go@noreply.github.com> Cc: Tronce <terryclark@westnet.com.au>, Author <author@noreply.github.com> Subject: Re: [mrpeel/smes-on-the-go] Hi Mr Peel can this Load on Android or is it only Iphone Friendly I cants get it to load on my Glalxsy s7 (#1) 
The application is just a mobile website so it's not platform specific.  I originally developed it when I had an LG Andoird phone and I now have a Oneplus Android phone and it works on both of those devices.
The only obvious thing to check is that you are using the Chrome browser.  I believe Samsung have their own browser.  I've only tested it using Chrome on Android, Chrome on iOS and Safari on iOs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrpeel/smes-on-the-go","title":"mrpeel/smes-on-the-go","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mrpeel/smes-on-the-go"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrpeel in #1: The application is just a mobile website so it's not platform specific.  I originally developed it when I had an LG Andoird phone and I now have a Oneplus Android phone and it works on both of those devices. \r\n\r\nThe only obvious thing to check is that you are using the Chrome browser.  I believe Samsung have their own browser.  I've only tested it using Chrome on Android, Chrome on iOS and Safari on iOs."}],"action":{"name":"View Issue","url":"https://github.com/mrpeel/smes-on-the-go/issues/1#issuecomment-283871233"}}}

**Comment by mrpeel** [comment]
I'm glad to hear you got it working.
