### ISSUE TITLE
Close button bug

### ISSUE THREAD

**Issue by lillypiri** [mrpeel/smes-on-the-go#2]
I’ve been using smes-on-the-go and really like it. I think there is a bug with the close button on info boxes.

After the map has loaded, and you click on a mark, the info box opens, and you can click the X and it closes it. If you do this again, the X no longer closes the info box, and will only close if you click on another mark, opening another info box. I’ve tested this locally and on your site. 

Using: 
Firefox 57.0.3 (64-bit)
Chrome 64.0.3282.167 (Official Build) (64-bit)

I have fixed it locally and will submit a PR in a moment, for you to look at.

**Comment by mrpeel** [comment]
Thanks for the fix.  I've merged it and redeployed the site.
